# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - azure-pipelines-*

resources:
  containers:
  - container: dev1
    image: quay.io/deis/go-dev:v1.19.1

jobs:
- job: unit_tests
  pool:
    vmImage: 'Ubuntu-16.04'
  #container: dev1

  variables:
    GOBIN:  '$(GOPATH)/bin' # Go binaries path
    GOROOT: '/usr/local/go1.11' # Go installation path # Go installation path
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/Azure/azure-container-networking' # $(build.repository.name)' # Path to the module's code

  steps:
  - script: |
      echo $UID
      sudo apt-get update
      sudo apt-get install -y ebtables ipset python3-dev gcc
      sudo pip install coverage
    displayName: 'Install OS dependencies'

  - script: |
      go version
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Set up the Go workspace'

  - script: |
      go get -v -t -d ./...
      if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
      fi
      go get github.com/docker/libnetwork/driverapi
      go get github.com/gorilla/mux
      go get golang.org/x/tools/cmd/cover
      go get github.com/jstemmer/go-junit-report
      go get github.com/axw/gocov/gocov
      go get github.com/AlekSi/gocov-xml
      go get -u gopkg.in/matm/v1/gocov-html
    workingDirectory: '$(modulePath)'
    displayName: 'Install Go dependencies'

  - script: |
      # sudo -E env "PATH=$PATH" go test -v ./ipam/ -coverprofile coverage-ipam.out
      # sudo -E env "PATH=$PATH" go test -v ./log/ -coverprofile coverage-log.out
      # sudo -E env "PATH=$PATH" go test -v ./netlink/ -coverprofile coverage-netlink.out
      # sudo -E env "PATH=$PATH" go test -v ./store/ -coverprofile coverage-store.out
      # sudo -E env "PATH=$PATH" go test -v ./telemetry/ -coverprofile coverage-telemetry.out
      # sudo -E env "PATH=$PATH" go test -v ./cnm/network/ -coverprofile coverage-network.out
      # sudo -E env "PATH=$PATH" go test -v ./cni/ipam/ -coverprofile coverage-ipam.out
      # sudo -E env "PATH=$PATH" go test -v ./cns/ipamclient/ -coverprofile coverage-ipamclient.out
      # sudo -E env "PATH=$PATH" go test -v ./npm/iptm/ -coverprofile coverage-iptm.out
      # sudo -E env "PATH=$PATH" go test -v ./npm/ipsm/ -coverprofile coverage-ipsm.out
      # sudo -E env "PATH=$PATH" go test -v ./npm/ -coverprofile coverage-npm.out
      # #sudo -E env "PATH=$PATH" go test -v ./cns/restserver/ -coverprofile coverage-restserver.out
      sudo -E env "PATH=$PATH" go test -v -coverprofile=coverage.txt -covermode count \
        ./ipam/ \
        ./log/ \
        ./netlink/ \
        ./store/ \
        ./telemetry/ \
        ./cnm/network/ \
        ./cni/ipam/ \
        ./cns/ipamclient/ \
        ./npm/iptm/ \
        ./npm/ipsm/ \
        ./npm > report.out
        cat report.out
        cat report.out | go-junit-report > report.xml
      gocov convert coverage.txt > coverage.json
      gocov-xml < coverage.json > coverage.xml
      mkdir coverage
      gocov-html < coverage.json > coverage/index.html
      #bash < (curl -s https://codecov.io/bash)
    workingDirectory: '$(modulePath)'
    displayName: 'Run test'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml

  - script: |
      sudo -E env "PATH=$PATH" make all-binaries
    workingDirectory: '$(modulePath)'
    displayName: 'Build'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'azure-vnet-cni'
      targetPath: '$(modulePath)/output/linux_amd64/cni/azure-vnet'